spring.application.name=flutter-crud

spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XE

spring.datasource.username=C##CRUD

spring.datasource.password=123

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
